### ISSUE TITLE
build breaks on node.js 0.10.36 install in pacman "Unrecognized archive format"

### ISSUE THREAD

**Issue by vielmetti** [nieleyde/rpi-nodered#1]
```
Step 8 : RUN pacman -U http://rollback.archlinuxarm.org/2015/02/15/armv6h/community/nodejs-0.10.36-3-armv6h.pkg.tar.xz --noconfirm
 ---> Running in a9564fa023b9
error: could not open file /var/cache/pacman/pkg/nodejs-0.10.36-3-armv6h.pkg.tar.xz: Unrecognized archive format
error: '/var/cache/pacman/pkg/nodejs-0.10.36-3-armv6h.pkg.tar.xz': cannot open package file
```

**Comment by vielmetti** [comment]
From the looks of things on http://archlinuxarm.org/packages there's no longer support in Arch Linux ARM for Node.JS 0.10.36. (There's a node.js 0.8 and a node.js 0.12 but not an 0.10.)

I know that there are said to be some issues as of yet unresolved in the move to support node.js 0.12 in Node-RED, what better time to test and find some bugs in that! But I would kind of like to get the 0.10.x version of node.js loaded and working too.

Thanks so much for the Dockerfile, this speeds up a project I'm working on immensely.

**Comment by nieleyde** [comment]
I was pulling nodejs from ArchLinux rollback machine, but it seems to have disappeared.  Let me know if you find a solution.

**Comment by vielmetti** [comment]
Found this forum where people were having a similar issue, but not really an answer. http://archlinuxarm.org/forum/viewtopic.php?f=15&t=8478

**Comment by vielmetti** [comment]
and I found the rollback machine for x86 for nodejs at http://seblu.net/a/arm/packages/n/nodejs/ but no ARM packages there. Curious.

**Comment by vielmetti** [comment]
Even more curious is http://www.adminempire.com/arch-linux-arm-rollback-machine/ which announces an ARM rollback machine, but the link is broken.

**Comment by vielmetti** [comment]
ah, more docs here

https://wiki.archlinux.org/index.php/Downgrading_packages

describe how to pull old packages out of your package cache. If you still have the old Node.JS for ARM distribution tarball on disk somewhere on your machine we can stick it somewhere for the build.

**Comment by vielmetti** [comment]
Closing this as you have moved to a raspbian based distribution instead of Arch.
